- job:
    name: my-test-job
    run: playbooks/my-test-playbook.yaml
    nodeset:
      nodes:
        - name: primary
          label: ubuntu-jammy
          
          
- project:
    name: my-project
    gh_check:
      jobs:
        - my-test-job
    gh_gate:
      jobs:
        - my-test-job
    gh_post:
      jobs:
        - my-test-job
    gh_tag:
      jobs:
        - my-test-job
